### ISSUE TITLE
How to register an API key?

### ISSUE THREAD

**Issue by herovan83** [svo80/vti_search#1]
When installing for the first time, the part to register the API did not appear.

How can I update the API key with the -u option? (I would like a command sample.)
![image](https://user-images.githubusercontent.com/51123323/108162811-30bd9880-7131-11eb-8669-01a7671bae8c.png)

Your program is really cool.

**Comment by svo80** [comment]
Hi,

Thank you very much for the nice feedback!

Could you please confirm that you installed the keyring package? Could you please also include some additional details about the system you are running this on? 

Regardless of this, if you are not seeing the request to enter the API key at all, there appears to be an issue. Happy to look into it in one of the next days. Thank you for reaching out!

**Comment by herovan83** [comment]
Thanks for the answer.
When I checked again regarding the Keyring package, pip3 --version came out as 3.6 So I changed pip3 --version to 3.7 and it runs normally.

**If ok, is there a sample for the -u option to update or change the API Key?**
Thanks

**Comment by svo80** [comment]
Could you please try a command such as:

`python3 vti_search.py -u -q 44d88612fea8a8f36de82e1278abb02f`

You should then see a prompt to update the API key. Please let me know if this works. Regardless of this, it sounds like there might still be an issue when keyring is not properly available. I will look into this in one of the next days.

**Comment by herovan83** [comment]
A command you gave me works very well.
Thank you
