### ISSUE TITLE
Private API key is so expensive

### ISSUE THREAD

**Issue by XuanRay** [svo80/vti_search#2]
40000+$ dollars per year.
Have other idea to obtain the private key?

**Comment by svo80** [comment]
Apologies, but this is not an issue.
The VirusTotal Private API is a service for professional threat intelligence and other security operations. Packages depending on use and requirements must be discussed with VirusTotal directly.

If you are solely interested in analyzing samples from certain malware campaigns, different universities and other third parties have published reference sets and _malware zoos_ for research purposes. This is a good start, and you can use, e.g., [Viper](https://github.com/viper-framework/viper) or similar free solutions for artifact management.

All the best
