### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by adelacruz400** [svo80/vti_search#3]
Does this work  if ran on windows (pycharm)? having issues..

**Comment by svo80** [comment]
What kind of issues do you have?
And no, I do not think that it runs on Windows unless the respective packages have been ported and installed. This program has been written for the Linux environment. 
You can easily set up a virtual machine in your Windows environment with a Linux operating system though.

**Comment by adelacruz400** [comment]
So inside the pycharm gui, I ran a search query then it cmd terminal pops up quick and just closes..

**Comment by adelacruz400** [comment]
It looks like it does something and creates a folder, but I wonder If it is possible to print the output of the query if saving it to the supposed destination folder is not possible?

**Comment by svo80** [comment]
Pycharm is a code editor. You should have a basic understanding how to execute a Python program. If you send me an error log or something similar, I can potentially advise. Other than though, this is a program for the Linux environment.

**Comment by adelacruz400** [comment]
![Capture1](https://user-images.githubusercontent.com/102551408/179085599-97635ea4-7a06-43e9-866e-c92bb50c33cd.PNG)
![Capture1](https://user-images.githubusercontent.com/102551408/179085599-97635ea4-7a06-43e9-866e-c92bb50c33cd.PNG)

**Comment by adelacruz400** [comment]
sorry newb here, but I think it does execute, just not sure where the output goes?

**Comment by svo80** [comment]
I am a nice guy, I generally try to help ;) Results are saved in the downloads subfolder with the respective timestamps. Please note, however, that you do need a VirusTotal Private API key. The program tries to help with professional use cases in the Threat Intelligence and cyber security area, i.e., you should know what kind of data you can get with VirusTotal and how you interpret it.

**Comment by adelacruz400** [comment]
Yep I know you are judging from your avatar :).  Yes it asked me when I first ran the code and I put in the key.  The subfolders content are empty though..

**Comment by svo80** [comment]
Just to confirm: You are using Python 3? Did you install the vt-py package (I am not sure if Windows is supported though).
It would help to run the program via a standard command line and paste the output. (If Pycharm supports pausing before the terminal window is closed, this should work, too).
Generally though, I am a bit skeptical if the program can be successfully run via Windows. I can try myself though in one of the next days.

**Comment by adelacruz400** [comment]
Yep installed as specified. if I just ran the code w/o the query..

**Comment by adelacruz400** [comment]
![p1](https://user-images.githubusercontent.com/102551408/179230018-af48974c-c7c4-4d16-8db8-8042de3eee4c.PNG)
![p1](https://user-images.githubusercontent.com/102551408/179230018-af48974c-c7c4-4d16-8db8-8042de3eee4c.PNG)

**Comment by svo80** [comment]
Yes, as I thought, the program is finishing with an error code under Windows. I can potentially check in one of the next days, but I currently do not have strong plans to make the tool also compatible to non-Linux systems. Do you have the chance setting up a Linux virtual machine, or is this not an option?

**Comment by adelacruz400** [comment]
Yes, but I will still need to ask permission, did you develop other tools for windows?

**Comment by svo80** [comment]
For security operations, I tend to work with Linux, and Windows is not so much a focus. The majority of tools that I wrote is not publicly available though.

**Comment by adelacruz400** [comment]
I understand, unfortunately we are windows shop.
